[project]
name = "alphapumphunter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "brotli>=1.2.0",
    "curl-cffi>=0.14.0",
    "fastapi>=0.135.2",
    "httpx[socks]>=0.25",
    "loguru>=0.7",
    "pybit>=5.10",
    "uptime-kuma-api>=1.2.1",
    "uvicorn>=0.42.0",
]
